env:
  browser: true
  es6: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'
plugins:
  - '@typescript-eslint'
settings:
  jsdoc:
    tagNamePreference:
      returns: 'return'
